apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: 976193264242.dkr.ecr.us-west-2.amazonaws.com/node-eks-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
